=== KarinaSafonenko/WebXML/in/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/medicines"
        xmlns:tns="http://www.example.com/medicines"
        elementFormDefault="qualified">
    <element name="medicines">
        <complexType>
            <sequence>
                <element ref="tns:medicine"  maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="medicine" type="tns:Medicine"  abstract="true"/>
    <complexType name="Medicine">
        <sequence>
            <element name="dosage" type="tns:Dosage" />
            <element name="fabricators">
                <complexType>
                    <sequence>
                        <element name="fabricator" type="tns:Fabricator" maxOccurs="unbounded" />
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="id" type="ID"  use="required"/>
        <attribute name="name" type="string" use="required" />
    </complexType>
    <complexType name="Analog">
        <attribute name="substitute" type="string" use="required" />
    </complexType>
    <complexType name="Fabricator">
        <sequence>
            <element name="certificate" type="tns:Certificate"/>
            <element name="versions">
                <complexType>
                    <sequence>
                        <element name="version" type="tns:Version" maxOccurs="unbounded" />
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="pharm" type="string" use="required" />
    </complexType>
    <complexType name="Version">
        <sequence>
            <element name="packs">
                <complexType>
                    <sequence>
                        <element name="pack" type="tns:Package" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="form" type="tns:Letters" use="required" />
    </complexType>
    <complexType name="Dosage">
        <attribute name="portion" type="string" use="required"/>
        <attribute name="period" type="string" use="required" />
    </complexType>
    <complexType name="Certificate">
        <attribute name="number" type="ID" use="required" />
        <attribute name="issue" type="date"/>
        <attribute name="expiration" type="date" use="required" />
    </complexType>
    <complexType name="Package">
        <sequence>
            <element name="type" default="tough">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="tough"></enumeration>
                        <enumeration value="semi-rigid"></enumeration>
                        <enumeration value="soft"></enumeration>
                    </restriction>
                </simpleType>
            </element>
            <element name="quantity" type="tns:Number-Text" />
            <element name="price" type="tns:Number-Text" />
        </sequence>
    </complexType>
    <simpleType name="Letters">
        <restriction base="string">
            <pattern value="\s*[a-zA-Zа-яА-Я]+\s*"></pattern>
        </restriction>
    </simpleType>
    <simpleType name="Number-Text">
        <restriction base="string">
            <pattern value="\s*(\d+|\d+\.\d+)\s+[a-zA-Zа-яА-Я]+\s*"></pattern>
        </restriction>
    </simpleType>
    <complexType name="Medicament">
        <complexContent>
            <extension base="tns:Medicine">
               <sequence>
                   <element name="group" type="string" />
                   <element name="analogs">
                       <complexType>
                           <sequence>
                               <element name="analog" type="tns:Analog" maxOccurs="unbounded" />
                           </sequence>
                       </complexType>
                   </element>
               </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="medicament" type="tns:Medicament" substitutionGroup="tns:medicine"></element>
    <complexType name="Supplement">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="vitamins">
                        <complexType>
                            <sequence>
                                <element name="vitamin" type="string" maxOccurs="unbounded" />
                            </sequence>
                        </complexType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="supplement" type="tns:Supplement" substitutionGroup="tns:medicine"></element>

</schema>

=== KarinaSafonenko/WebXML/in/test.xml
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.example.com/medicines"
           xsi:schemaLocation="http://www.example.com/medicines  medicines.xsd">
    <medicament id="medsn001" name="Kaptopril">
        <dosage portion="6-12 mg." period="3 times a day"/>
        <fabricators>
            <fabricator pharm="Farmacor production">
                <certificate number="a1332" issue=" 2017-02-05" expiration="2018-03-05"/>
                <versions>
                    <version form="pills">
                        <packs>
                            <pack>
                                <type>tough</type>
                                <quantity>20 pieces</quantity>
                                <price>3 rub</price>
                            </pack>
                            <pack>
                                <type>tough</type>
                                <quantity>40 pieces</quantity>
                                <price>5 rub</price>
                            </pack>
                        </packs>
                    </version>
                </versions>
            </fabricator>
            <fabricator pharm="Farmland">
                <certificate number="akj32" issue="2017-02-01" expiration="2019-03-25"/>
                <versions>
                    <version form="pills">
                        <packs>
                            <pack>
                                <type>tough</type>
                                <quantity>50 pieces</quantity>
                                <price>2.14 rub</price>
                            </pack>
                            <pack>
                                <type>tough</type>
                                <quantity>20 pieces</quantity>
                                <price>1.74 rub</price>
                            </pack>
                        </packs>
                    </version>
                </versions>
            </fabricator>
        </fabricators>
        <group>Ingibitor</group>
        <analogs>
            <analog substitute="Angiopril"></analog>
            <analog substitute="Blocordil"></analog>
            <analog substitute="Kapoten"></analog>
        </analogs>
    </medicament>
    <medicament id="medsn002" name="Cetrifacson">
        <dosage portion="1-2 g." period="3 times a day"/>
        <fabricators>
            <fabricator pharm="Shrea Life">
                <certificate number="jhd89" issue="2017-01-05" expiration="2019-03-05"/>
                <versions>
                    <version form="powder">
                        <packs>
                            <pack>
                                <type>semi-rigid</type>
                                <quantity>50 pieces</quantity>
                                <price>823 rub</price>
                            </pack>
                        </packs>
                    </version>
                    <version form="flacon">
                        <packs>
                            <pack>
                                <type>semi-rigid</type>
                                <quantity>1 piece</quantity>
                                <price>35 rub</price>
                            </pack>
                        </packs>
                    </version>
                </versions>
            </fabricator>
        </fabricators>
        <group>Ingibitor</group>
        <analogs>
            <analog substitute="Loracson"></analog>
            <analog substitute="Sulbatrokson"></analog>
        </analogs>
    </medicament>
    <supplement name="Fish fat" id="hgf3">
        <dosage portion="1-2 capsule" period="2-3 times a day"/>
        <fabricators>
            <fabricator pharm="RealCaps">
                <certificate number="fkj78" expiration="2019-03-03"/>
                <versions>
                    <version form="capsule">
                        <packs>
                            <pack>
                                <type>tough</type>
                                <quantity>30 pieces</quantity>
                                <price>4.04 rub</price>
                            </pack>
                        </packs>
                    </version>
                </versions>
            </fabricator>
        </fabricators>
        <vitamins>
            <vitamin>Vitamin A</vitamin>
            <vitamin>Vitamin D</vitamin>
        </vitamins>
    </supplement>
</medicines>
